services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=video
    ports:
      - "3306:3306"
  api:
    build: ./video_api
    ports:
      - "8000:8000"
    volumes:
      - ./video_api:/code
    depends_on:
      - database
    restart: always
  